export const INTERNAL_SIDEBAR_LEFT_WIDTH = 420;
export const INTERNAL_SIDEBAR_LEFT_COLLAPSED_WIDTH = 72;

export const INTERNAL_SIDEBAR_RIGHT_WIDTH = 420;
export const INTERNAL_SIDEBAR_RIGHT_COLLAPSED_WIDTH = 0;
